### ISSUE TITLE
Return delay for driving_function_imp_localwfs()

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-matlab#121]
`driving_function_imp_wfs()` and `driving_function_imp_nfchoa()` now both return their processing delay in seconds as last output parameter. This is missing for `driving_function_imp_localwfs()`.
@fietew: could you add this?

**Comment by hagenw** [comment]
As far as I see it this is solved, as both `driving_function_imp_localwfs_sbl()` and `driving_function_imp_localwfs_vss()` return a `delay_offset` parameter.
@fietew can this be closed?

**Comment by fietew** [comment]
Yes
