### ISSUE TITLE
WFS 2.5D focused source time driving function does not match theory

### ISSUE THREAD

**Issue by chris-hld** [sfstoolbox/sfs-matlab#123]
For 2.5-D WFS, getting the time based driving signals for a focused virtual source:

- g0 of the [default implementation](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_fs.m#L145) does not match the referenced equation in the
[docu](http://sfstoolbox.org/en/latest/#equation-d.wfs.fs.2.5D).

I tried both, and there is a difference in resulting amplitude.
Which one should be preferred?

**Comment by hagenw** [comment]
Interesting. This should be fixed in #124

**Comment by fietew** [comment]
Imho, the documentation is wrong not g0 in the code.

**Comment by hagenw** [comment]
The documentation is in line with Schultz (2016), or do we have the same problem there that the values are defined differently? I'm also not sure if the equations in Verheijen (1997) and Start (1997) are different due to other definitions of the distances or if they are really different ;)

**Comment by fietew** [comment]
Does Schultz (2016) cover focused sources at all?

**Comment by hagenw** [comment]
It doesn't, but as it should be only the time reversed version and `|x0-xs|` and `|xref-x0|` should be ok, as the sign does not matter.

**Comment by fietew** [comment]
If you do the math, especially the stationary phase approximation, there is a difference which stems from the time reversal. For the exponential term inside the synthesis integral you get exp(-j k (|x0 - xs| + |x0 - x|)) for a point source and exp(-j k (- |x0 - xs| + |x0 - x|)) for a focussed source. The second distance term |x0-x| is the green's function on the boundary and does not change with time reversal. The argument of the expentional directly corresponds to the denominator of g0.

**Comment by hagenw** [comment]
OK, I have now tested it with `test_wfs_25d()` and looked at the fact that the source in inside the listening area. Now, I would also say that the implementation is correct and the documentation is wrong. I will create a pull request for the documentation.

**Comment by fs446** [comment]
Nope

**Comment by hagenw** [comment]
This is now fixed.
