### ISSUE TITLE
Asymmetry of mono-frequent and time domain LSFS driving functions

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-matlab#139]
By comparing [`driving_function_mono_localwfs()`](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_monochromatic/driving_function_mono_localwfs.m) and [`driving_function_imp_localwfs()`](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_time_domain/driving_function_imp_localwfs.m) I was wondering why they look so different.

I haven't figured out all the points, but I would like to start with two questions:

1) In `driving_function_mono_localwfs()` you use `driving_function_mono_wfs()` to get [the driving signals of the virtual sources](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_monochromatic/driving_function_mono_localwfs.m#L99). In `driving_function_imp_localwfs()` you use a [big `if` clause](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_time_domain/driving_function_imp_localwfs.m#L114) to get the delays and weights for every single source type.
Could you maybe replace this by `[~,tauv,wv] = driving_function_imp_wfs(xv,xs,src,virtualconf);`?

2) In `driving_function_mono_localwfs()` you use `virtualconf` to [calculate the driving signals for the virtual sources](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_monochromatic/driving_function_mono_localwfs.m#L99). In `driving_function_imp_localwfs()` you use `conf` to [do the same](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_time_domain/driving_function_imp_localwfs.m#L119).

**Comment by fietew** [comment]
Yeah, I have already made some changes to align frequency and time implementations inside a local branch on my machine. These changes however build up on #135. I will tackle this after the merge of #135 into master.

**Comment by hagenw** [comment]
The points I have mentioned are now tackled by #140.

I guess the only remaining difference is now, that not all driving functions are implemented in the mono-frequency domain yet.

**Comment by hagenw** [comment]
This was basically handled by #140.
What is missing at the moment is an implementation of ´driving_function_mono_localwfs_sbl()´.
@fietew is this planned in the near future, should I create a new dedicated issue for this, or should we simply close this issue?

**Comment by fietew** [comment]
I am not sure, when I will have time for this. I think we don't need a dedicated issue and we can close this issue.
