### ISSUE TITLE
Delayline section in SFS_config.m

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-matlab#163]
The [delayline section config section](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_config.m#L102-L133) in `SFS_config.m` is difficult to understand if you are not an expert in this area. For example, it is not clear what might be a good setting for fractional delays. Is this done with purpose, because it heavily depends on the application. Or is it save to add a comment indicating a good default fractional delay setting?

In addition, I was wondering if it would help to move the [`conf.delayline.filter` section](https://github.com/sfstoolbox/sfs-matlab/blob/master/SFS_config.m#L121-L128) to the beginning of the delayline section?

**Comment by fietew** [comment]
> The delayline section config section in SFS_config.m is difficult to understand if you are not an expert in this area. For example, it is not clear what might be a good setting for fractional delays. Is this done with purpose, because it heavily depends on the application. Or is it save to add a comment indicating a good default fractional delay setting?

I could add the settings, which I usually use, when I want to be sure, that the fractional delay interpolation has no influence on the simulation result. The simulation will be rather slow, but it might be the best solution, if you don't have a clue, what to choose. One could also cite the paper https://doi.org/10.1109/EUSIPCO.2016.7760682 to show, that the necessary interpolation accuracy highly depends on the actual use case and parametrisation.

> In addition, I was wondering if it would help to move the conf.delayline.filter section to the beginning of the delayline section?

Yes, good idea.

**Comment by hagenw** [comment]
Done.
