### ISSUE TITLE
Implementation the code using the Julia programming language 

### ISSUE THREAD

**Issue by feima0011** [sfstoolbox/sfs-matlab#181]
The sfs matlab is a good project, but using the matlab/octave programming language.
The matlab software costs a lot, and matlab/octave is too slow.

Implementation the code using the Julia programming language will be good.

Julia is fast, and free. 

https://julialang.org/

**Comment by hagenw** [comment]
Thanks for your interest in sfs.

When we started the project roughly ten years ago Julia was not available and also python was not as good for signal processing as it is now. There is also nothing wrong with using Octave as speed is not a main concern for most of the functionality of the toolbox.

Nonetheless, in 2015 we started a python version of the toolbox: https://github.com/sfstoolbox/sfs-python, which is in our opinion a better choice for this project than Julia as you can produce better readable code and profit from its large community.
